"""Evidence-first Career Studio core."""

from .domain import (
    AddedKeyword,
    AssertedFact,
    CareerClaim,
    CandidateEdge,
    CareerMatchResult,
    ClaimContext,
    ClaimObject,
    ClaimPredicate,
    ClaimSubject,
    ClaimSubjectKind,
    ClaimValueKind,
    CoverageBand,
    CoverageSummary,
    DraftBullet,
    DraftTransformation,
    MatchStrength,
    RequirementCategory,
    RequirementPriority,
    ResumeDraft,
    RoleRequirement,
    ScoreComponents,
    SelectedMatch,
    SourceSpan,
    TemporalScope,
    stable_claim_id,
    stable_draft_id,
)
from .matching import match_requirements, score_candidate_edge
from .validation import validate_draft
from .writing import draft_from_matches
from .workflow import (
    CareerDeliverable,
    CareerSpecialist,
    CareerSpecialistResponse,
)

__all__ = [
    "AddedKeyword",
    "AssertedFact",
    "CareerClaim",
    "CareerDeliverable",
    "CandidateEdge",
    "CareerMatchResult",
    "CareerSpecialist",
    "CareerSpecialistResponse",
    "ClaimContext",
    "ClaimObject",
    "ClaimPredicate",
    "ClaimSubject",
    "ClaimSubjectKind",
    "ClaimValueKind",
    "CoverageBand",
    "CoverageSummary",
    "DraftBullet",
    "DraftTransformation",
    "MatchStrength",
    "RequirementCategory",
    "RequirementPriority",
    "ResumeDraft",
    "RoleRequirement",
    "ScoreComponents",
    "SelectedMatch",
    "SourceSpan",
    "TemporalScope",
    "match_requirements",
    "score_candidate_edge",
    "stable_claim_id",
    "stable_draft_id",
    "draft_from_matches",
    "validate_draft",
]
