"""Evidence-first Career Studio core."""

from .domain import (
    CareerClaim,
    CandidateEdge,
    CareerMatchResult,
    ClaimContext,
    ClaimObject,
    ClaimPredicate,
    ClaimSubject,
    ClaimSubjectKind,
    ClaimValueKind,
    CoverageBand,
    CoverageSummary,
    MatchStrength,
    RequirementCategory,
    RequirementPriority,
    RoleRequirement,
    ScoreComponents,
    SelectedMatch,
    SourceSpan,
    TemporalScope,
    stable_claim_id,
)
from .matching import match_requirements, score_candidate_edge

__all__ = [
    "CareerClaim",
    "CandidateEdge",
    "CareerMatchResult",
    "ClaimContext",
    "ClaimObject",
    "ClaimPredicate",
    "ClaimSubject",
    "ClaimSubjectKind",
    "ClaimValueKind",
    "CoverageBand",
    "CoverageSummary",
    "MatchStrength",
    "RequirementCategory",
    "RequirementPriority",
    "RoleRequirement",
    "ScoreComponents",
    "SelectedMatch",
    "SourceSpan",
    "TemporalScope",
    "match_requirements",
    "score_candidate_edge",
    "stable_claim_id",
]
